-- Independent Damage Log schema
CREATE TABLE IF NOT EXISTS `damage_log_entries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `map` VARCHAR(32) NOT NULL DEFAULT '',
  `x` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `y` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `owner_account_id` INT UNSIGNED NOT NULL,
  `owner_char_id` INT UNSIGNED NOT NULL,
  `owner_name` VARCHAR(24) NOT NULL DEFAULT '',
  `owner_job_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `owner_job_name` VARCHAR(32) NOT NULL DEFAULT '',
  `target_type` VARCHAR(12) NOT NULL DEFAULT 'OTHER',
  `target_account_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `target_char_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `target_name` VARCHAR(24) NOT NULL DEFAULT '',
  `target_mob_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `target_job_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `target_job_name` VARCHAR(32) NOT NULL DEFAULT '',
  `skill_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `skill_name` VARCHAR(64) NOT NULL DEFAULT '',
  `skill_side` VARCHAR(12) NOT NULL DEFAULT 'user',
  `damage_type` VARCHAR(12) NOT NULL DEFAULT 'unknown',
  `damage_nature` VARCHAR(12) NOT NULL DEFAULT 'unknown',
  `damage_dealt` BIGINT NOT NULL DEFAULT 0,
  `damage_taken` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_dmg_owner_time` (`owner_char_id`,`created_at`),
  KEY `idx_dmg_target_time` (`target_name`,`created_at`),
  KEY `idx_dmg_skill` (`skill_id`,`created_at`),
  KEY `idx_dmg_owner_nature_time` (`owner_char_id`,`damage_nature`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
