# rev24 battleground stats persistence baseline.

CREATE TABLE IF NOT EXISTS `char_bg` (
  `char_id` INT(11) NOT NULL,
  `win` INT(11) NOT NULL DEFAULT 0,
  `lost` INT(11) NOT NULL DEFAULT 0,
  `tie` INT(11) NOT NULL DEFAULT 0,
  `deserter` INT(11) NOT NULL DEFAULT 0,
  `score` INT(11) NOT NULL DEFAULT 0,
  `points` INT(11) NOT NULL DEFAULT 0,
  `rank_points` INT(11) NOT NULL DEFAULT 0,
  `rank_games` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`char_id`)
) ENGINE=InnoDB;

ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `win` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `deserter` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `score` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `points` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `rank_points` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `rank_games` INT(11) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `char_wstats` (
  `char_id` INT(11) NOT NULL,
  `score` INT(11) NOT NULL DEFAULT 0,
  `points` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`char_id`)
) ENGINE=InnoDB;

ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `score` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `points` INT(11) NOT NULL DEFAULT 0;
