-- Idempotent schema migration for EasyCore Battleground rev24 stats tables.
-- Source reference: diffs/Battleground-EasyCore-21-24 [OK]/Serverside/sql/extended_bg.sql

CREATE TABLE IF NOT EXISTS `char_bg` (
  `char_id` INT(11) NOT NULL,
  PRIMARY KEY (`char_id`)
) ENGINE=InnoDB;

ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `top_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `damage_done` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `damage_received` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `skulls` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ti_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ti_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ti_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `eos_flags` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `eos_bases` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `eos_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `eos_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `eos_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `boss_killed` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `boss_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `boss_flags` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `boss_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `boss_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `boss_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `dom_bases` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `dom_off_kills` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `dom_def_kills` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `dom_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `dom_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `dom_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `td_kills` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `td_deaths` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `td_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `td_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `td_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sc_stole` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sc_captured` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sc_droped` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sc_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sc_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sc_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ctf_taken` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ctf_captured` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ctf_droped` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ctf_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ctf_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ctf_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `emperium_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `barricade_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `gstone_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `cq_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `cq_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ru_captures` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ru_wins` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ru_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `kill_count` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `death_count` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `win` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `leader_win` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `leader_lost` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `leader_tie` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `deserter` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `score` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `points` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `rank_points` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `rank_games` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sp_heal_potions` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `hp_heal_potions` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `yellow_gemstones` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `red_gemstones` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `blue_gemstones` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `poison_bottles` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `acid_demostration` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `acid_demostration_fail` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `support_skills_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `healing_done` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `wrong_support_skills_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `wrong_healing_done` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `sp_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `zeny_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `spiritb_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `ammo_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_bg` ADD COLUMN IF NOT EXISTS `showstats` INT(11) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `char_wstats` (
  `char_id` INT(11) NOT NULL,
  PRIMARY KEY (`char_id`)
) ENGINE=InnoDB;

ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `top_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `damage_done` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `damage_received` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `emperium_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `guardian_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `barricade_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `gstone_damage` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `emperium_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `guardian_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `barricade_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `gstone_kill` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `sp_heal_potions` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `hp_heal_potions` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `yellow_gemstones` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `red_gemstones` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `blue_gemstones` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `poison_bottles` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `acid_demostration` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `acid_demostration_fail` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `support_skills_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `healing_done` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `wrong_support_skills_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `wrong_healing_done` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `sp_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `zeny_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `spiritb_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `ammo_used` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `kill_count` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `death_count` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `score` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `points` INT(11) NOT NULL DEFAULT 0;
ALTER TABLE `char_wstats` ADD COLUMN IF NOT EXISTS `showstats` INT(11) NOT NULL DEFAULT 0;
